#! /bin/bash
for i in 1 2 3 4 5 6 7 8 9
do
        echo $i
done


#! /bin/bash
for i in {1..20}
do
        echo $i
done


#! /bin/bash
for i in {1..50..3}
do
        echo $i
done


#! /bin/bash
for (( i=0; i<=10; i++ ))
do
        echo $i
done

#To execute command in for loop 

#! /bin/bash
for command in ls pwd date df
do
        echo "*********$command*********"
        $command
done

#To get items in particular directory
# -d to get directories
# -f to get files

#! /bin/bash
for item in *
do
        if [ -d $item ]
        then
                echo $item
        fi
done


#To check bash version 
echo ${BASH_VERSION}
