#! /bin/bash
while read p
do
        echo $p
done < condi.sh


#Using cat command

#! /bin/bash
cat while.sh | while read p
do
        echo $p
done


#Using IFS - Internal Field Seperator

#! /bin/bash
while IFS=  read p
do
        echo $p
done < /etc/hosts
