#! /bin/bash
n=1
while [ $n -le 10 ]
do
        echo "$n"
        n=$(( n+1 ))
done


# While with sleep

#! /bin/bash
n=1
while [ $n -le 10 ]
do
        echo "$n"
        n=$(( n+1 ))
        sleep 1
done
